# 3. 넘파이(NumPy)
다차원배열과 수학 함수를 제공하는 모듈, 라이브러리

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3], dtype=np.float32)
b = np.array([1, 2, 3], dtype=np.int32)

In [3]:
print(a, a.dtype)
print(b, b.dtype)

[1. 2. 3.] float32
[1 2 3] int32


In [4]:
c = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
print(c)

[[1 2 3]
 [4 5 6]]


In [6]:
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [7]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a = np.arange(10)
b = np.arange(1, 11)
c = np.arange(1, 11, 2)

In [11]:
a, b, c

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([1, 3, 5, 7, 9]))

In [12]:
score = np.array([85, 90, 78, 92, 88])

In [13]:
score

array([85, 90, 78, 92, 88])

In [14]:
heights = np.array([160, 165, 170, 175, 180])

In [15]:
heights

array([160, 165, 170, 175, 180])

In [16]:
prices = np.array([1200, 1500, 1800, 2100])

In [17]:
prices

array([1200, 1500, 1800, 2100])

In [18]:
temps = np.array([20, 22, 19, 25, 30])

In [19]:
temps

array([20, 22, 19, 25, 30])

In [20]:
a = np.arange(0, 5)

In [21]:
a

array([0, 1, 2, 3, 4])

In [22]:
b = np.arange(0, 10)

In [23]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
c = np.arange(3, 8)

In [25]:
c

array([3, 4, 5, 6, 7])

In [26]:
d = np.arange(-2, 3)

In [27]:
d

array([-2, -1,  0,  1,  2])

In [39]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.dtype)
print(b.ndim)
print(b.shape)

int64
2
(2, 3)


In [46]:
arr = np.array([1.1, 2.1, 3.1])

arr2 = arr.astype(np.int32)
arr2
arr2.dtype

dtype('int32')

In [47]:
lis = [1, 2, 3]

In [48]:
for i in lis:
    print(i+3)

4
5
6


In [52]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a > b

array([False, False, False])

In [54]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a[0]

np.int64(0)

In [58]:
a[3:6]

array([3, 4, 5])

In [59]:
a[1] = 99

In [60]:
a

array([ 0, 99,  2,  3,  4,  5,  6,  7,  8,  9])

In [61]:
a[3:6] = 88, 77, 66

In [62]:
a

array([ 0, 99,  2, 88, 77, 66,  6,  7,  8,  9])

In [63]:
a[:]

array([ 0, 99,  2, 88, 77, 66,  6,  7,  8,  9])

In [66]:
a[:] = 999

In [67]:
a

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

In [69]:
arr = np.array([10, 20, 30, 40, 50])

In [70]:
arr[0]

np.int64(10)

In [71]:
arr[2]

np.int64(30)

In [72]:
arr[-1]

np.int64(50)

In [75]:
arr[1] = 200
arr

array([ 10, 200,  30,  40,  50])

In [76]:
arr[3] = 999
arr

array([ 10, 200,  30, 999,  50])

In [77]:
arr = np.array(['가', '나', '다', '라', '마'])

In [79]:
arr[1]

np.str_('나')

In [80]:
arr[3]

np.str_('라')

In [81]:
arr[-1]

np.str_('마')

In [88]:
arr[0] = '하'
arr

array(['하', '나', '호', '라', '마'], dtype='<U1')

In [89]:
arr[2] = '호'
arr

array(['하', '나', '호', '라', '마'], dtype='<U1')

In [90]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

In [92]:
arr[:3]

array([10, 20, 30])

In [94]:
arr[3:]

array([40, 50, 60, 70])

In [96]:
arr[1:5]

array([20, 30, 40, 50])

In [97]:
arr = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g'])

In [99]:
arr[:3]

array(['a', 'b', 'c'], dtype='<U1')

In [101]:
arr[3:]

array(['d', 'e', 'f', 'g'], dtype='<U1')

In [103]:
arr[1:5]

array(['b', 'c', 'd', 'e'], dtype='<U1')

In [104]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [111]:
arr[2][2]

np.int64(9)

In [130]:
arr[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [132]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [134]:
arr[0,1]

np.int64(20)

In [136]:
arr[2,0]

np.int64(70)

In [138]:
arr[1]

array([40, 50, 60])

In [142]:
arr[:,1]

array([20, 50, 80])

In [144]:
arr[0,2] = 300

In [145]:
arr

array([[ 10,  20, 300],
       [ 40,  50,  60],
       [ 70,  80,  90]])

In [146]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [147]:
arr[1, 2]

np.int64(7)

In [148]:
arr[3, 0]

np.int64(13)

In [150]:
arr[2]

array([ 9, 10, 11, 12])

In [151]:
arr[:, 3]

array([ 4,  8, 12, 16])

In [153]:
arr[0, 3] = 100

In [154]:
arr

array([[  1,   2,   3, 100],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16]])

In [155]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [157]:
arr[0,:2]

array([10, 20])

In [163]:
arr[1:]

array([[40, 50, 60],
       [70, 80, 90]])

In [164]:
arr[:, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [165]:
student = np.array(['철수', '영희', '민수', '철수', '철수'])
books = np.array([['수학의 정석', 7], ['해리포터', 10], ['파이썬 입문', 5], ['한국사', 5], ['데미안', 12]])

In [169]:
arr = (student == '철수')

In [171]:
books[arr]

array([['수학의 정석', '7'],
       ['한국사', '5'],
       ['데미안', '12']], dtype='<U21')

In [172]:
arr = (student != '철수')

In [173]:
books[arr]

array([['해리포터', '10'],
       ['파이썬 입문', '5']], dtype='<U21')

In [174]:
books == '수학의 정석'

array([[ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [177]:
books[books=='수학의 정석'] = '자바의 정석'

In [178]:
books

array([['자바의 정석', '7'],
       ['해리포터', '10'],
       ['파이썬 입문', '5'],
       ['한국사', '5'],
       ['데미안', '12']], dtype='<U21')

In [179]:
books[student != '철수'] = 7

In [180]:
books

array([['자바의 정석', '7'],
       ['7', '7'],
       ['7', '7'],
       ['한국사', '5'],
       ['데미안', '12']], dtype='<U21')

In [192]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

In [193]:
arr[arr > 30]

array([40, 50, 60, 70])

In [194]:
arr[arr % 2 == 0]

array([10, 20, 30, 40, 50, 60, 70])

In [195]:
arr[arr > 50] = 999

In [196]:
arr

array([ 10,  20,  30,  40,  50, 999, 999])

In [204]:
employees = np.array(['짱구', '철수', '유리', '맹구', '훈이'])
salaries = np.array([250, 320, 280, 400, 150])

In [205]:
salaries[employees == '맹구']

array([400])

In [206]:
employees[salaries > 300]

array(['철수', '맹구'], dtype='<U2')

In [208]:
salaries[salaries < 200] = 200

In [209]:
salaries

array([250, 320, 280, 400, 200])

In [211]:
arr = np.arange(1, 10).reshape(3, 3)

In [212]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [213]:
a = np.arange(1, 17).reshape(4, 4)

In [214]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [215]:
a = np.arange(1, 13).reshape(3, 4)

In [216]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [217]:
num = np.arange(12).reshape(3, 4)

In [218]:
num

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [219]:
num = np.arange(1, 17).reshape(4, 4)

In [220]:
num

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [222]:
num = np.arange(1, 21).reshape(5, 4)

In [223]:
num

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [224]:
num = np.arange(10, 26).reshape(4, 4)

In [225]:
num

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [226]:
arr = np.random.standard_normal(size=10)
arr

array([ 0.29791272, -1.59053127,  1.36394172,  0.25299262,  0.37432476,
        1.21303561, -0.26947192,  0.17362925,  0.08561062, -0.19451813])

In [228]:
arr = np.random.uniform(size=10)
arr

array([0.91602895, 0.62716271, 0.0840314 , 0.95837778, 0.87998281,
       0.29541426, 0.0443962 , 0.95974353, 0.13620678, 0.11002092])

In [229]:
arr = np.random.standard_normal(size=5)
arr

array([ 0.65072168,  0.99788254, -0.04802285, -0.79158754,  0.86090958])

In [231]:
arr = np.random.uniform(size=5)
arr

array([0.27420189, 0.61995504, 0.10872515, 0.53100443, 0.73895028])

In [235]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [237]:
np.add(arr, 3)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [240]:
a = np.array([5, 3, 7, 4, 10])
b = np.array([3, 4, 5, 6, 7])

In [241]:
np.maximum(a, b)

array([ 5,  4,  7,  6, 10])

In [243]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
cond = np.array([True, True, False])

In [244]:
np.where(cond, a, b)

array([ 1,  2, 30])

In [247]:
arr = np.array([-2, -1, 0, 1, 2])
np.where(arr > 0, 'o', 'x')

array(['x', 'x', 'x', 'o', 'o'], dtype='<U1')

In [257]:
arr = np.array([5, 12, 7, 20, 3])
np.where(arr > 10, 100, 0)

array([  0, 100,   0, 100,   0])

In [261]:
arr = np.array([15, 8, 22, 6, 13])
arr

array([15,  8, 22,  6, 13])

In [262]:
np.where(arr % 2 == 0, 1, -1)

array([-1,  1,  1,  1, -1])

In [263]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])
arr = np.array([True, False, True, False, True])
np.where(arr, a, b)

array([10,  2, 30,  4, 50])

In [264]:
lis = [1, 2, 3, 4, 5]
lis

[1, 2, 3, 4, 5]

In [269]:
sum = 0
for n in lis:
    sum = sum + n
print(sum)
print(sum / len(lis))

15
3.0


In [276]:
lis = np.array([1, 2, 3, 4, 5])
print(np.sum(lis))
print(np.mean(lis))
print(np.max(lis))
print(np.min(lis))

15
3.0
5
1


In [279]:
menu = np.array(['김밥', '라면', '떡볶이', '치킨'])
cal = np.array([250, 550, 400, 800])

In [280]:
np.sum(cal)

np.int64(2000)

In [281]:
np.mean(cal)

np.float64(500.0)

In [283]:
np.max(cal)

np.int64(800)

In [284]:
np.min(cal)

np.int64(250)

In [285]:
day = np.array(['월', '화', '수', '목', '금', '토', '일'])
tr_m = np.array([30, 45, 60, 20, 40, 50, 35])

In [286]:
np.sum(tr_m)

np.int64(280)

In [288]:
np.mean(tr_m)

np.float64(40.0)

In [289]:
np.max(tr_m)

np.int64(60)

In [291]:
np.min(tr_m)

np.int64(20)

In [295]:
arr = np.arange(1, 10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [298]:
arr.sum()

np.int64(45)

In [303]:
# axis=0 세로열, axis=1 가로행
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[12 15 18]
[ 6 15 24]


In [304]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.cumsum())

[ 1  3  6 10 15]


In [309]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(arr)
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]
